# Generated by Django 5.2.8 on 2026-01-15 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="master_icons/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Category Master",
                "verbose_name_plural": "Category Masters",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="sub_icons/"),
                ),
                (
                    "date_event",
                    models.DateField(
                        blank=True, help_text="Specific date for festivals", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="core.categorymaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Category",
                "verbose_name_plural": "Sub Categories",
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("GIF", "GIF"),
                            ("STICKER", "Sticker"),
                            ("QUOTE", "Text Quote"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="wishes/")),
                ("text_content", models.TextField(blank=True, null=True)),
                ("downloads", models.PositiveIntegerField(default=0)),
                ("shares", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="core.subcategory",
                    ),
                ),
            ],
        ),
    ]
