# Generated by Django 5.2.8 on 2026-01-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("IMAGE", "Image"),
                    ("GIF", "GIF"),
                    ("STICKER", "Sticker"),
                    ("QUOTE", "Text Quote"),
                    ("WRITE_NAME", "Write Name"),
                ],
                max_length=10,
            ),
        ),
    ]
