# Generated by Django 5.2.8 on 2026-01-24 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetailShareContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("gif", "GIF"),
                            ("sticker", "Sticker"),
                            ("quotes", "Quotes"),
                            ("writename", "Write Name"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("shared", "Shared"),
                            ("downloaded", "Downloaded"),
                            ("viewed", "Viewed"),
                        ],
                        default="shared",
                        max_length=20,
                    ),
                ),
                (
                    "data",
                    models.CharField(
                        help_text="Filename or Content Data", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.categorymaster",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.subcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity Log",
                "verbose_name_plural": "User Detail Share Content",
            },
        ),
    ]
