# Generated by Django 5.2.8 on 2026-01-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_userdetailsharecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetailsharecontent",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("shared", "Shared"),
                    ("downloaded", "Downloaded"),
                    ("viewed", "Viewed"),
                    ("favorited", "Favorited"),
                ],
                default="shared",
                max_length=20,
            ),
        ),
    ]
