"""
Django settings for wish2chat project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ayi+_p5*)$!emzc3wkdzu!spwi@)nb0=+%f!(565i$t0n*3s-6"

# SECURITY WARNING: don't run with debug turned on in production!
<<<<<<< HEAD
DEBUG = True

ALLOWED_HOSTS = ['*']

=======
DEBUG = False

ALLOWED_HOSTS = ['*', 'www.wish2chat.shreejifintech.com']

CSRF_TRUSTED_ORIGINS = [
    "https://www.wish2chat.shreejifintech.com",
]
>>>>>>> dcc7d36cc4db87bba79e05efded22a89b772b6fd

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "wish2chat.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
<<<<<<< HEAD
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
=======
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
>>>>>>> dcc7d36cc4db87bba79e05efded22a89b772b6fd
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wish2chat.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
<<<<<<< HEAD
        "OPTIONS": {
            "timeout": 20, # 20 seconds tak wait karega agar lock ho toh
        },
=======
>>>>>>> dcc7d36cc4db87bba79e05efded22a89b772b6fd
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True

# settings.py
DATETIME_FORMAT = "d M Y, P"  # e.g., 21 Feb 2026, 12:40 p.m.
USE_L10N = False  # Make Django use your DATETIME_FORMAT instead of locale default
USE_TZ = True

<<<<<<< HEAD

=======
>>>>>>> dcc7d36cc4db87bba79e05efded22a89b772b6fd
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

<<<<<<< HEAD
import os

=======
>>>>>>> dcc7d36cc4db87bba79e05efded22a89b772b6fd
# Base URL for serving media files
MEDIA_URL = '/media/'  # <--- MUST have slashes at start and end

# Path where media is stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication', # 👈 Enables Token Auth
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny', # Default to public, lock down specific views
    ],
}
<<<<<<< HEAD

# --- Real Gmail SMTP Configuration ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'shreejiaffiliate@gmail.com'
EMAIL_HOST_PASSWORD = 'cqalsnvodeavhxxa' # Google App Password
GOOGLE_OAUTH2_CLIENT_ID = "Y655836602340-rt68kot2cgjl4nub7ru91v71rkrtm7qm.apps.googleusercontent.com"
=======
# ✅ HTTPS FIX (important behind nginx)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ✅ COOKIES (production safe)
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
>>>>>>> dcc7d36cc4db87bba79e05efded22a89b772b6fd
